from pathlib import Path
import json,hashlib,re
ROOT=Path(__file__).resolve().parents[1];P=ROOT/'platform';G=ROOT/'reference/golden-r2'
plans=json.loads((G/'production-plans.json').read_text());rows=[]
def add(weight,bucket,owner,text):rows.append(dict(id=len(rows)+1,weight=weight,bucket=bucket,causal_owner=owner,text=text))
add(1,'package','execution','Executes the delivered offline optimizer with a documented command to generate the submitted case results; equivalent languages and source organization pass.')
add(1,'package','deliverables','Provides the six logical products as accessible files: optimizer, independent verifier, schedules, case matrix/selections, certification/traces/adversarial results, and memo. No particular filenames, schema or physical file count is required.')
add(1,'package','coverage','Identifies all24 distinct design/campaign cases: D0..D5 crossed with campaign0..3. Extra explanatory records pass when these cases are unambiguous.')
add(2,'local','graph','Recovers solid undirected edges {0-3,3-6,3-4,4-7,6-7,7-8,5-8,2-5,1-4}, adding only4-5 for open designs D3/D5. Node=3y+x, P=3,Q=5,K=1; equivalent labels pass with an explicit mapping.')
add(2,'local','workload','Generates lots j=0..4 for campaigns s=0..3 with family=(j+s)%2, release=2floor(j/2), Pbase=5+(j*j+2s)%4 and Qbase=4+(3j+s)%5. Equivalent formula notation passes.')
add(1,'local','design-input','Uses design inputs (F,G,aisle,capital): D0=(2,5,closed,0),D1=(3,5,closed,7),D2=(2,6,closed,9),D3=(2,5,open,6),D4=(3,6,closed,16),D5=(3,6,open,22).')
for field,label,owner in [('makespan','optimum makespan','makespan-results'),('bill','minimum bill at optimum makespan','bill-results')]:
    for d in range(6):
        profile=[p[field] for p in plans if p['design']==f'D{d}']
        unit='minutes' if field=='makespan' else 'benchmark cost units'
        add(2,'integrated',owner,f'Reports D{d} four-campaign {label} profile as {profile} {unit}, campaign order0,1,2,3. This is one design profile; separate rows, an equivalent table or another explicit ordering pass. Any attaining schedule passes.')
add(1,'integrated','boundary','Resets production state separately for every case and completes operations at boundary t before simultaneous starts/actions occupying [t,t+1); a duration-d operation occupies [t,t+d). Starts use resources released at t, and execution ends at the final cure boundary.')
add(1,'integrated','preparation','Assigns each lot in executed preparation once to P or Q after release, with at most one uninterrupted setup-plus-processing operation per machine; the machine frees on completion and prepared output waits in an unlimited buffer.')
add(1,'integrated','setup','Initializes executed machine family memory unset, updates it at preparation start, retains it through idle, and applies setup0 initially/on unchanged family or2 on a change; processing duration is the generated duration for the selected machine.')
add(1,'integrated','fixtures','Keeps executed fixture holdings at most F; each lot holds one continuously from preparation start through waits, transport and curing, releasing only at cure completion.')
add(1,'integrated','robot-actions','Starts executed robots empty at nodes3 and5 with fixed identities and executes exactly one one-minute wait, adjacent drawn-edge move, pickup or unload action per minute. Pickup/unload/wait remain at the node; empty repositioning is allowed and locations persist.')
add(1,'integrated','cargo-precedence','Executes pickups taking one prepared untransported lot at its source using an empty robot; cargo capacity is one and duplicate pickup is forbidden. Pickup becomes cargo at t+1; unloading occurs only at K and makes the lot available for curing at t+1. Every lot is conserved through its stages.')
add(1,'integrated','collision','Uses each undirected edge in executed routes at most once per minute, forbidding both swaps and same-direction sharing; boundary node capacity is1 except P/Q/K capacity2. Following into a vacated node is legal.')
add(1,'integrated','batch','Selects at executed oven starts one or two arrived uncured same-family lots while the oven is idle; membership stays fixed for4+family minutes, then all members finish together. Waiting arrivals do not automatically start curing.')
add(1,'integrated','power','Respects aggregate G in every executed minute including ongoing operations and all new starts/actions: P=2,Q=3,oven=3,robot move/pick/unload=1 each, wait=0; setup draws full machine power and other idle resources draw zero.')
add(1,'integrated','objective-arithmetic','Computes makespan as final cure boundary and bill as sum over t=0..M-1 of total minute power times 1+(floor(t/7)%3). This checks arithmetic on delivered schedules independently of whether they are optimal.')
add(2,'integrated','verifier-independence','Delivers and executes a separately runnable verifier that independently reconstructs constraints and checks; shared material with the optimizer is limited to immutable instance data. Equivalent complete-certificate checkers pass; a wrapper importing optimizer transitions, feasibility or pruning does not establish independence.')
add(10,'integrated','makespan-proof','Independently establishes the minimum makespan for all24 cases through executed complete search excluding earlier completion or a checked complete mathematical certificate, with justified state merging/pruning. Feasible schedules, labels or hashes alone do not prove optimality; equivalent complete proof methods pass.')
add(10,'integrated','bill-proof','Independently establishes the minimum bill at the minimum makespan for all24 cases through executed complete cost search or a checked complete mathematical certificate. This grades complete independent evidence, not another copy of the numerical result; equivalent complete proof methods pass.')
add(2,'integrated','trace','Produces chronological traces from the delivered uninterrupted schedules with starts/completions, both robot positions/cargo, active preparation/oven work, fixtures, minute power and cumulative bill; final time/bill reconcile with case records. Equivalent nesting, compression and simultaneous-event ordering pass.')
add(2,'decision','unrestricted-selection','Applies the lexicographic key (max of four makespans,sum of four bills+3capital,capital,ID) to all six designs and selects its minimum. Grade selection arithmetic/population on delivered metrics without charging an upstream metric error again; with correct metrics the result is D5,(33,1116,22,D5).')
add(2,'decision','budget-selection','Minimizes the lexicographic key (max of four makespans,sum of four bills+3capital,capital,ID) within capital<=9, including equality and hence D0,D1,D2,D3. Grade population/selection on delivered metrics without recharging upstream metric errors; with correct metrics the result is D1,(37,1110,7,D1).')
add(1,'decision','baseline-comparison','Compares D0 with both selected designs using the delivered executed objectives. Accept a comparison that is correct relative to delivered results despite an upstream optimization error; do not require additional design pairs.')
add(2,'decision','causal-explanation','Explains at least one actual routing, batching or resource interaction using identifiable event times from delivered production schedules, connecting it to the engineering recommendation. Accept any accurate supported interaction; no particular reference route or unrequested comparison is mandatory.')
add(1,'decision','relaxation','Explains that distance-only travel omits shared undirected-edge and interior-node occupancy interactions, so its bound alone cannot certify a feasible joint robot schedule or achieved completion time.')
add(1,'integrated','negative-start','Executes a copied-production-schedule test changing its earliest preparation start to-1; verifier rejects the copy and accepts the preserved original. Equivalent test harnesses pass.')
add(1,'integrated','collision-test','Executes a copied-production-route mutation causing an edge or interior-node conflict; verifier rejects it, identifies the first invalid action minute or clearly mapped boundary, and preserves the accepted original. Either collision type suffices.')
add(1,'package','reproduction','Records optimizer/verifier reproduction commands and actual tool versions, sufficient to regenerate the delivered files in the declared offline environment.')
add(-8,'negative','embedded-answer','Embeds precomputed case-result values or schedule tables as substitutes for executing the optimizer that produces reported results. Immutable input constants and computed search caches do not trigger this active-behavior trap; omission alone does not trigger it.')
assert len(rows)==41 and sum(max(0,r['weight']) for r in rows)==77
(P/'rubric.json').write_text(json.dumps(rows,indent=2)+'\n')
(P/'rubric.md').write_text('# R2-F1 rubric — frozen before local blind calibration\n\nPositive total77; negative trap-8. Criteria are binary. Local normalization is earned positive points minus triggered penalty, divided by77, clamped at zero. This is an explicitly labelled local measure; official source material does not specify a complete platform normalization formula. Accept equivalent correct work. Report a supplemental generous proportional score for incomplete objective profiles/proof coverage; a low binary score alone cannot establish difficulty if substantial correct work is hidden by an incomplete profile. No hidden file/schema/route requirements.\n\n'+'\n\n'.join(f"{r['id']}. **{r['weight']:+d}** — {r['text']}" for r in rows)+'\n')
flows=json.loads((ROOT/'audit/rejected-rubric-draft/ideal-flow.json').read_text())
flows['Execute and Generate']=flows['Execute and Generate'].replace('Run the negative-start and collision mutations and preserve their first invalid minute.','Run the negative-start and collision mutations, preserving the originals; identify the collision mutation\'s first invalid minute.')
flows['Execute & Generate']=flows.pop('Execute and Generate')
flows={key:flows[key] for key in ('Analyze','Execute & Generate','Synthesize')}
flows['Synthesize']='Use executed optimal results to recommend D5 with key (33,1116,22,D5), and choose D1 under capital<=9 with key (37,1110,7,D1). Compare D0 against both selected designs using their executed objectives. Explain at least one actual routing, batching or resource interaction using event times from delivered schedules, and connect it to the recommendation. Explain why distance-only travel is a lower bound rather than a joint collision-feasible routing certificate. Reconcile schedules, traces, metrics, proofs and selection arithmetic. Describe an executed debugging or adversarial-check iteration. Any accurate supported interaction is acceptable; no particular route, optimal schedule or additional design comparison is required.'
(P/'ideal-flow.json').write_text(json.dumps(flows,indent=2)+'\n');(P/'ideal-flow.md').write_text('\n\n'.join(f'## {k}\n\n```text\n{v}\n```' for k,v in flows.items())+'\n')
print('criteria',len(rows),'positive',77,'prompt_words',len((P/'prompt.md').read_text().split()),'flow_lengths',{k:len(v) for k,v in flows.items()})
